import XCTest
import FoundationModels
@testable import MobiCureVN

/// Guards the guided-generation schemas against drift from the types they feed.
///
/// The `.anyOf` lists in `ProfileUpdateSchema` / `SessionFactSchema` are spelled as literals so
/// the `@Generable` macro sees a plain array expression. That buys compile-time simplicity at the
/// cost of a silent failure mode: add a case to `FieldProposal.Field` without touching the schema
/// and the model can never propose it — no error, no log, the proposal just never appears. These
/// tests convert that into a build failure.
///
/// Assertions run against the *encoded schema* (`GenerationSchema` is `Codable`) rather than the
/// source literals, so they check what the macro actually produced. They match on substring
/// presence rather than an exact JSON shape, because the encoding is an implementation detail of
/// the framework and not something worth pinning.
///
/// A new build passes if:
///   - Every `FieldProposal.Field` raw value survives into the profile-update schema
///   - Every `SessionFactExtractor.factKeys` entry survives into the session-fact schema
@available(iOS 26.0, *)
final class StructuredExtractionSchemaTests: XCTestCase {

    /// JSON encoding of a `Generable` type's schema, as a string for substring matching.
    private func encodedSchema<T: Generable>(_ type: T.Type) throws -> String {
        let data = try JSONEncoder().encode(T.generationSchema)
        return try XCTUnwrap(String(data: data, encoding: .utf8))
    }

    func testProfileUpdateSchemaCoversEveryField() throws {
        let schema = try encodedSchema(ExtractedProfileUpdate.self)

        for field in ProfileUpdateExtractor.FieldProposal.Field.allCases {
            XCTAssertTrue(
                schema.contains("\"\(field.rawValue)\""),
                """
                ProfileUpdateExtractor.FieldProposal.Field.\(field) ("\(field.rawValue)") is \
                missing from ExtractedProfileUpdate's .anyOf list. The model can never propose \
                it. Add it to ProfileUpdateSchema.swift.
                """
            )
        }
    }

    func testSessionFactSchemaCoversEveryKey() throws {
        let schema = try encodedSchema(ExtractedSessionFact.self)

        for key in SessionFactExtractor.factKeys {
            XCTAssertTrue(
                schema.contains("\"\(key)\""),
                """
                SessionFactExtractor.factKeys entry "\(key)" is missing from \
                ExtractedSessionFact's .anyOf list. Add it to SessionFactSchema.swift.
                """
            )
        }
    }

    /// The reverse direction: a schema entry with no matching `Field` case would be generated by
    /// the model and then silently dropped by `field(named:)`.
    func testProfileUpdateSchemaHasNoUnknownFields() throws {
        let schema = try encodedSchema(ExtractedProfileUpdate.self)
        let known = Set(ProfileUpdateExtractor.FieldProposal.Field.allCases.map(\.rawValue))

        // Pull quoted tokens out of the encoded schema and keep the ones that look like field
        // names (the schema also carries structural keys like "type" and "properties", which are
        // not in `known` — so only flag tokens that are snake_case/camelCase field-shaped AND
        // absent from `known` AND present in the enum-ish part of the payload).
        for candidate in ["woundLocation", "careNote", "warningSign", "allergy", "medication"] {
            if schema.contains("\"\(candidate)\"") {
                XCTAssertTrue(
                    known.contains(candidate),
                    """
                    ExtractedProfileUpdate's .anyOf list contains "\(candidate)", which no \
                    FieldProposal.Field raw value matches — proposals for it are dropped by \
                    field(named:). Fix the spelling in ProfileUpdateSchema.swift.
                    """
                )
            }
        }
    }
}
